# Generated by Django 3.1 on 2020-12-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijacomplainer', '0004_auto_20201221_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainer',
            name='sector',
            field=models.CharField(choices=[('W', 'Works'), ('P', 'Power'), ('T', 'Transportation'), ('E', 'Education')], max_length=20, null=True),
        ),
    ]
