# Generated by Django 3.2 on 2021-04-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijacomplainer', '0008_auto_20210220_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complainer',
            options={'ordering': ['-id', '-time']},
        ),
        migrations.AddField(
            model_name='complainer',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
