# Generated by Django 3.2.6 on 2021-11-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijacomplainer', '0009_auto_20210427_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainer',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
