# Generated by Django 4.0.4 on 2022-05-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijacomplainer', '0010_complainer_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainer',
            name='images',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
