# Generated by Django 4.0.4 on 2022-06-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijacomplainer', '0011_complainer_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainer',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
