# Generated by Django 4.0.4 on 2022-07-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijacomplainer', '0012_alter_complainer_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainer',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
